server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      auto-index-creation: true

jwt:
  secret: dhsajdJDHSAKDHjsahdjsahdkjsahJDSAHK2312312dashdjahakjdak8767678123kdsa